# Generated by Django 5.2.1 on 2025-06-10 09:48

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook profile URL', null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram profile URL', null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Phone number (e.g., +201234567890)', max_length=128, null=True, region='EG'),
        ),
        migrations.AddField(
            model_name='profile',
            name='whatsapp_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='WhatsApp number (e.g., +201234567890)', max_length=128, null=True, region='EG'),
        ),
    ]
