# Generated by Django 5.2.1 on 2025-06-11 02:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(300)]),
        ),
    ]
