# Generated by Django 5.2.1 on 2025-06-11 02:53

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='facebook_url',
            field=models.URLField(blank=True, default='', help_text='Facebook profile URL', validators=[django.core.validators.URLValidator()]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='instagram_url',
            field=models.URLField(blank=True, default='', help_text='Instagram profile URL', validators=[django.core.validators.URLValidator()]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', help_text='Phone number (e.g., +201234567890)', max_length=128, region='EG'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='whatsapp_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', help_text='WhatsApp number (e.g., +201234567890)', max_length=128, region='EG'),
            preserve_default=False,
        ),
    ]
