# Generated by Django 5.2.1 on 2025-05-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('max_persons', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trip_date', models.DateField()),
                ('destinations', models.TextField(help_text='Describe all places you will visit')),
                ('contact_info', models.CharField(max_length=100)),
            ],
        ),
    ]
