# Generated by Django 5.2.1 on 2025-06-06 02:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('max_persons', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trip_date_start', models.DateField()),
                ('trip_date_end', models.DateField()),
                ('city', models.CharField(max_length=100)),
                ('destinations', models.TextField(help_text='Describe all places you will visit')),
                ('contact_info', models.CharField(max_length=100)),
                ('trip_picture', models.ImageField(blank=True, null=True, upload_to='trip_pictures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
