# Generated by Django 5.2.1 on 2025-06-06 04:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_trip_max_persons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='max_persons',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999999)]),
        ),
    ]
