# Generated by Django 5.2.1 on 2025-06-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_trip_max_persons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='city',
            field=models.CharField(max_length=20),
        ),
    ]
