# Generated by Django 5.2.1 on 2025-06-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_alter_trip_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='contact_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
