# Generated by Django 5.2.1 on 2025-06-11 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_alter_trip_contact_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='contact_info',
        ),
    ]
