# Generated by Django 5.2.1 on 2025-06-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_trip_description_alter_trip_destinations_tripday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='description',
        ),
        migrations.AlterField(
            model_name='trip',
            name='destinations',
            field=models.TextField(help_text='Describe all places you will visit'),
        ),
        migrations.DeleteModel(
            name='TripDay',
        ),
    ]
