# Generated by Django 5.2.1 on 2025-06-11 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_remove_trip_description_alter_trip_destinations_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='destinations',
            new_name='description',
        ),
    ]
